# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2I4rkIr3suiwVzgb1iYLjsckk1e_aya
"""

import pandas as pd
import random

frutas = ["maçã", "banana", "laranja", "uva", "maçã", "melão", "mamão", "banana"]

quantidades = {}

print(" Quantidades geradas por ocorrência:")
for fruta in frutas:
    qtd = random.randint(0, 100)
    print(f" - {fruta}: {qtd}")
    if fruta in quantidades:
        quantidades[fruta] += qtd
    else:
        quantidades[fruta] = qtd

print("\n Quantidades finais após a soma:")
for fruta, quantidade in quantidades.items():
    print(f" - {fruta}: {quantidade}")

with open("minhas_frutas.txt", "w", encoding="utf-8") as file:
    for fruta, quantidade in quantidades.items():
        file.write(f"{fruta},{quantidade}\n")

print("\n Conteúdo do arquivo minhas_frutas.txt:")
with open("minhas_frutas.txt", "r", encoding="utf-8") as file:
    linhas = file.readlines()
    for i, linha in enumerate(linhas, start=1):
        print(f"{i}: {linha.strip()}")

dados = []

with open("minhas_frutas.txt", "r", encoding="utf-8") as file:
    for linha in file:
        fruta, quantidade = linha.strip().split(",")
        dados.append((fruta, int(quantidade)))

df = pd.DataFrame(dados, columns=["Fruta", "Quantidade"])

print("\n DataFrame Final:")
print(df)