# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sF0IPakr4av0llrbPHgD01Cis5MIIPKZ
"""

import pandas as pd
import numpy as np
import joblib
from sklearn.tree import DecisionTreeClassifier

def gerar_csv():
    dados = [
        (18.5, False), (19.5, False), (20.5, False), (22.0, False),
        (24.0, False), (25.5, True), (27.0, True), (30.0, True),
        (32.5, True), (35.0, True)
    ]
    df = pd.DataFrame(dados, columns=["IMC", "Obeso"])
    df.to_csv("imc_obesidade.csv", index=False)

def treinar_modelo():
    df = pd.read_csv("imc_obesidade.csv")
    X = df[["IMC"]]
    y = df["Obeso"]
    modelo = DecisionTreeClassifier()
    modelo.fit(X, y)
    joblib.dump(modelo, "modelo_imc.pkl")

def prever_obesidade(imc):
    if not isinstance(imc, (int, float)) or imc <= 0:
        return "Erro: IMC inválido. Digite um número positivo."

    modelo = joblib.load("modelo_imc.pkl")
    previsao = modelo.predict(np.array([[imc]]))
    return "Obeso" if previsao[0] else "Não obeso"

gerar_csv()
treinar_modelo()

try:
    imc_usuario = float(input("Digite seu IMC: "))
    print(f"IMC: {imc_usuario} - {prever_obesidade(imc_usuario)}")
except ValueError:
    print("Erro: Por favor, insira um número válido.")