# -*- coding: utf-8 -*-
"""Dever-01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVNbVMruE2XTXRbSa-tueSvEDCFTUvR5
"""

!/usr/share/locales/install-language-pack pt_BR

!dpkg-reconfigure locales

os.kill(os.getpid(), 9)

import pandas as pd

dados = {
    "Nome": ["João", "Pedro", "Júlia", "Neymar", "Marcos"],
    "Data_Nascimento": ["10/07/1994", "15/12/2002", "11/08/1995", "02/02/1987", "18/09/1979"],
    "Dia_Cadastro": ["2025-02-19", "2025-02-20", "2025-02-21", "2025-02-22", "2025-02-23"],
    "Hora_Cadastro": ["16:00:00", "09:35:00", "10:20:00", "12:00:00", "09:50:00"]
}

df = pd.DataFrame(dados)
df.to_csv("cadastro.csv", index=False)

df = pd.read_csv("cadastro.csv")

while True:
    try:
        n = int(input("Digite o número do registro (0 a 4): "))

        if 0 <= n < len(df):
            break
        else:
            print("Número fora do intervalo! Digite um número entre 0 e 4.")
    except ValueError:
        print("Entrada inválida! Digite apenas números entre 0 e 4.")


nome = df.loc[n, "Nome"]
nascimento = df.loc[n, "Data_Nascimento"]
dia_cadastro = df.loc[n, "Dia_Cadastro"]
hora_cadastro = df.loc[n, "Hora_Cadastro"]


ano, mes, dia = dia_cadastro.split("-")
data_cadastro_formatada = f"{dia}/{mes}/{ano}"


print(f"Registro: {nome}, nascido em {nascimento}, cadastrado em {data_cadastro_formatada} às {hora_cadastro}.")