# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYmmd9bSnHq0bR39wl6hosoB-SG8SV06
"""

import csv

def criar_arquivo_csv():
    with open("dados.csv", mode="w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow(["Nome", "Idade"])
        writer.writerows([
            ["Ana", 25],
            ["Bruno", 30],
            ["Carla", 22],
            ["Daniel", 28],
            ["Eduardo", 35]
        ])

def ler_arquivo_csv():
    dados = []
    with open("dados.csv", mode="r", encoding="utf-8") as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            dados.append((row[0], int(row[1])))
    return dados

def buscar_nome(dados, nome):
    idades = [idade for _, idade in dados]
    idade_maxima = max(idades)

    for pessoa, idade in dados:
        if pessoa.lower() == nome.lower():
            if idade == idade_maxima:
                print(f"{pessoa} tem {idade} anos, é a pessoa mais velha da lista.")
            else:
                print(f"{pessoa} tem {idade} anos, não é a pessoa mais velha da lista.")
            return
    print("Nome não encontrado.")


criar_arquivo_csv()

dados = ler_arquivo_csv()

nome_digitado = input("Digite um nome: ")
buscar_nome(dados, nome_digitado)