# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbOXo3Mn9KnSgNZUaaiUcwZaHkS_1Iof
"""

def obter_frase():

    while True:
        frase = input("Digite uma frase: ").strip()
        if frase:
            return frase
        else:
            print("Entrada inválida! Por favor, digite uma frase válida.")


def analisar_frase(frase):

    num_caracteres = len(frase)
    palavras = frase.split()
    num_palavras = len(palavras)
    maior_palavra = max(palavras, key=len) if palavras else ""
    frase_invertida_caracteres = frase[::-1]
    frase_invertida_palavras = " ".join(reversed(palavras))
    frase_maiuscula = frase.upper()
    frase_minuscula = frase.lower()
    tupla_palavras = tuple(palavras)

    return {
        "num_caracteres": num_caracteres,
        "num_palavras": num_palavras,
        "maior_palavra": maior_palavra,
        "frase_invertida_caracteres": frase_invertida_caracteres,
        "frase_invertida_palavras": frase_invertida_palavras,
        "frase_maiuscula": frase_maiuscula,
        "frase_minuscula": frase_minuscula,
        "tupla_palavras": tupla_palavras,
    }


def exibir_resultados(resultados):

    print("\n--- RESULTADOS DA ANÁLISE ---")
    print(f"Número de caracteres: {resultados['num_caracteres']}")
    print(f"Número de palavras: {resultados['num_palavras']}")
    print(f"Maior palavra: {resultados['maior_palavra']}")
    print(f"Frase invertida por caracteres: {resultados['frase_invertida_caracteres']}")
    print(f"Frase invertida por palavras: {resultados['frase_invertida_palavras']}")
    print(f"Frase em maiúsculas: {resultados['frase_maiuscula']}")
    print(f"Frase em minúsculas: {resultados['frase_minuscula']}")
    print(f"Tupla de palavras: {resultados['tupla_palavras']}")


def main():

    frase = obter_frase()
    resultados = analisar_frase(frase)
    exibir_resultados(resultados)


if __name__ == "__main__":
    main()